name: tian_key
description: "Tian Key V11 Mazda Axela BLE Controller App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_blue_plus: ^1.34.5    # 稳定兼容版 BLE 蓝牙插件（已升级以解决云端编译报错）
  vibration: ^1.8.4             # 稳定版触觉震动反馈
  shared_preferences: ^2.2.2    # 本地数据与密码存储

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/borrow_page_bg.png
    - assets/home_car_bg.png
    - assets/home_controls_bg.png
    - assets/logo_footer_bg.png
    - assets/popup_admin_auth.png
    - assets/popup_device_name.png
    - assets/popup_edit_pwd.png
    - assets/popup_reset_pwd.png
    - assets/popup_sound.png
    - assets/popup_time_sync.png
    - assets/settings_auto_connect.png
    - assets/settings_page_bg.png
