name: tian_key

description: "Tian Key V11 Mazda Axela BLE Controller App"

publish_to: "none"

version: 1.0.0+1


environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8


  # 蓝牙 BLE
  flutter_blue_plus: ^1.35.3


  # 本地保存
  shared_preferences: ^2.5.3


  # 震动反馈
  vibration: ^2.0.0


dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true


  assets:

    - assets/
