name: tian_key
description: "Tian Key V11 终极冻结版汽车钥匙控制APP"
publish_to: 'none'
version: 1.1.0+11

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.6  # 用于 ESP32 蓝牙 BLE 通信
  shared_preferences: ^2.2.2  # 用于本地安全存储管理员密码与配置

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # 注册赛博机械风 UI 切片与背景图资产
  assets:
    - assets/images/
